### PR TITLE
Update haproxy template

### PR DESCRIPTION
**Pull request by gnuoy**
Update haproxy template to be compatible with reative adapters

### CODE REVIEW

**Comment by ajkavanagh** [comment]
I've noticed that it uses `options.` in the haproxy.cfg, but this may not be necessary as the fields are present (I think?) directly due to the configuration adapter placing them on the instance as attributes?

**Comment by gnuoy** [comment]
The 'options.' is necessary as that's the namespace the config parameters are placed it.

**Comment by ajkavanagh** [comment]
Okay, looks good. +1

**Comment by gnuoy** [comment]
[gnuoy, r=ajkavanagh]

**Pull request merged**
